<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BookTicketImplService" targetNamespace="http://service.poc.venkat.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.poc.venkat.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://service.poc.venkat.com/" schemaLocation="bookticket_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="cancelTicket">
    <wsdl:part name="parameters" element="tns:cancelTicket">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="bookTicket">
    <wsdl:part name="parameters" element="tns:bookTicket">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="bookTicketResponse">
    <wsdl:part name="parameters" element="tns:bookTicketResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="cancelTicketResponse">
    <wsdl:part name="parameters" element="tns:cancelTicketResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="BookTicket">
    <wsdl:operation name="bookTicket">
      <wsdl:input name="bookTicket" message="tns:bookTicket">
    </wsdl:input>
      <wsdl:output name="bookTicketResponse" message="tns:bookTicketResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cancelTicket">
      <wsdl:input name="cancelTicket" message="tns:cancelTicket">
    </wsdl:input>
      <wsdl:output name="cancelTicketResponse" message="tns:cancelTicketResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BookTicketImplServiceSoapBinding" type="tns:BookTicket">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="bookTicket">
      <soap:operation soapAction="urn:BookTicket" style="document"/>
      <wsdl:input name="bookTicket">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="bookTicketResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="cancelTicket">
      <soap:operation soapAction="urn:CancelTicket" style="document"/>
      <wsdl:input name="cancelTicket">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="cancelTicketResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BookTicketImplService">
    <wsdl:port name="BookTicketImplPort" binding="tns:BookTicketImplServiceSoapBinding">
      <soap:address location="http://10.224.202.86:8181/bookTicketWithServiceMix/services/BookTicketImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
